spring:
  application:
   name: config-service

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka